server:
  port: 8081

spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.example.payments.wallet: DEBUG
