apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ledger-service
  template:
    metadata:
      labels:
        app: ledger-service
    spec:
      containers:
      - name: ledger-service
        image: ledger-service:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://ledger-db:5432/ledger_db
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka:9092
---
apiVersion: v1
kind: Service
metadata:
  name: ledger-service
spec:
  selector:
    app: ledger-service
  ports:
  - port: 8082
    targetPort: 8082
