
jdbc:
  datasource-proxy:
    enabled: true

spring:
  application:
    name: payment-service


  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    template:
      observation-enabled: true
    listener:
      observation-enabled: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus # Otwiera endpoint /actuator/prometheus
  metrics:
    tags:
      application: ${spring.application.name} # Ułatwi filtrowanie w Grafanie
  tracing:
    sampling:
      probability: 1.0 # 100% zapytań jest śledzonych (na produkcję daje się np. 0.1)
  otlp:
    tracing:
      # Celuje w Tempo w namespace 'monitoring'
      endpoint: http://tempo.monitoring.svc.cluster.local:4318/v1/traces


server:
  port: 8080

wallet:
  service:
    url: ${WALLET_SERVICE_URL:http://localhost:8081}

grpc:
  client:
    authorization-service:
      address: ${GRPC_AUTHORIZATION_SERVICE_ADDRESS:static://authorization-service:9091}
      negotiation-type: ${GRPC_AUTHORIZATION_SERVICE_NEGOTIATION_TYPE:plaintext}
    fee-service:
      address: ${GRPC_FEE_SERVICE_ADDRESS:static://fee-service:9091}
      negotiation-type: ${GRPC_FEE_SERVICE_NEGOTIATION_TYPE:plaintext}
    fraud-service:
      address: ${GRPC_FRAUD_SERVICE_ADDRESS:static://fraud-service:9091}
      negotiation-type: ${GRPC_FRAUD_SERVICE_NEGOTIATION_TYPE:plaintext}
    fx-service:
      address: ${GRPC_FX_SERVICE_ADDRESS:static://fx-service:9091}
      negotiation-type: ${GRPC_FX_SERVICE_NEGOTIATION_TYPE:plaintext}
    limits-service:
      address: ${GRPC_LIMITS_SERVICE_ADDRESS:static://limits-service:9091}
      negotiation-type: ${GRPC_LIMITS_SERVICE_NEGOTIATION_TYPE:plaintext}
    sanctions-service:
      address: ${GRPC_SANCTIONS_SERVICE_ADDRESS:static://sanctions-service:9091}
      negotiation-type: ${GRPC_SANCTIONS_SERVICE_NEGOTIATION_TYPE:plaintext}
    wallet-service:
      address: ${GRPC_WALLET_SERVICE_ADDRESS:static://wallet-service:9090}
      negotiation-type: ${GRPC_WALLET_SERVICE_NEGOTIATION_TYPE:plaintext}

logging:
  level:
    com.example.payments: DEBUG
    org.springframework.statemachine: WARN
