CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id TEXT UNIQUE NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    currency TEXT NOT NULL CHECK (char_length(currency) = 3),
    state TEXT NOT NULL,
    reject_reason TEXT,
    source_currency TEXT,
    source_amount NUMERIC(19, 4),
    exchange_rate NUMERIC(19, 6),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS payment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    from_state TEXT,
    to_state TEXT NOT NULL,
    event TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT UNIQUE NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    gross_amount NUMERIC(19, 4) NOT NULL,
    percentage_fee NUMERIC(19, 4) NOT NULL,
    flat_fee NUMERIC(19, 4) NOT NULL,
    total_fee NUMERIC(19, 4) NOT NULL,
    net_amount NUMERIC(19, 4) NOT NULL,
    currency TEXT NOT NULL CHECK (char_length(currency) = 3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT UNIQUE NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    score INT NOT NULL,
    risk_level TEXT NOT NULL,
    recommendation TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payment_history_payment_id ON payment_history(payment_id);
CREATE INDEX IF NOT EXISTS idx_payment_fees_payment_id ON payment_fees(payment_id);
CREATE INDEX IF NOT EXISTS idx_fraud_records_payment_id ON fraud_records(payment_id);

CREATE TABLE IF NOT EXISTS payer_profiles (
    payer_id BIGINT PRIMARY KEY,
    segment TEXT NOT NULL,
    kyc_status TEXT NOT NULL
);
