CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id TEXT UNIQUE NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    currency TEXT NOT NULL CHECK (char_length(currency) = 3),
    state TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS payment_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    region TEXT NOT NULL,
    from_state TEXT,
    to_state TEXT NOT NULL,
    event TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_fees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT UNIQUE NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    gross_amount NUMERIC(19, 4) NOT NULL,
    percentage_fee NUMERIC(19, 4) NOT NULL,
    flat_fee NUMERIC(19, 4) NOT NULL,
    total_fee NUMERIC(19, 4) NOT NULL,
    net_amount NUMERIC(19, 4) NOT NULL,
    currency TEXT NOT NULL CHECK (char_length(currency) = 3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS fraud_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id BIGINT UNIQUE NOT NULL REFERENCES payments(id) ON DELETE CASCADE,
    score INT NOT NULL,
    risk_level TEXT NOT NULL,
    recommendation TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_payment_history_payment_id ON payment_history(payment_id);
CREATE INDEX IF NOT EXISTS idx_payment_fees_payment_id ON payment_fees(payment_id);
CREATE INDEX IF NOT EXISTS idx_fraud_records_payment_id ON fraud_records(payment_id);

-- Migration DDL for existing database instances
ALTER TABLE payments DROP COLUMN IF EXISTS version;

ALTER TABLE payment_history ADD COLUMN IF NOT EXISTS region TEXT DEFAULT 'ROOT';

UPDATE payment_history SET region = CASE
    WHEN to_state IN ('AUTH_PENDING', 'AUTH_APPROVED', 'AUTH_REJECTED', 'AUTHORIZED') THEN 'Authorization'
    WHEN to_state IN ('FRAUD_EVALUATING', 'FRAUD_PASSED', 'FRAUD_DETECTED') THEN 'FraudCheck'
    WHEN to_state IN ('LIMITS_EVALUATING', 'LIMITS_OK', 'LIMITS_EXCEEDED') THEN 'LimitsCheck'
    WHEN to_state IN ('SANCTIONS_EVALUATING', 'SANCTIONS_CLEARED', 'SANCTIONS_HIT') THEN 'SanctionsCheck'
    WHEN to_state IN ('FEE_EVALUATING', 'FEE_CALCULATED', 'FEE_CHARGED', 'FEE_FAILED') THEN 'FeeCheck'
    ELSE 'ROOT'
END WHERE region IS NULL OR region = 'ROOT';

ALTER TABLE payment_history ALTER COLUMN region SET NOT NULL;
