package com.example.payment.domain.enums;

public enum PaymentState {
    NEW,
    PENDING,
    PROCESSING,

    AUTH_PENDING,
    AUTH_APPROVED,
    AUTH_REJECTED,
    AUTH_FAILED,

    FRAUD_EVALUATING,
    FRAUD_PASSED,
    FRAUD_FAILED,
    FRAUD_DETECTED,

    LIMITS_EVALUATING,
    LIMITS_OK,
    LIMITS_EXCEEDED,
    LIMITS_FAILED,

    SANCTIONS_EVALUATING,
    SANCTIONS_CLEARED,
    SANCTIONS_HIT,
    SANCTIONS_FAILED,

    FEE_EVALUATING,
    FEE_CALCULATED,
    FEE_CHARGED,
    FEE_FAILED,

    FX_CONVERSION,
    AUTHORIZED,
    COMPENSATING,

    FEE_EVALUATING_COMPENSATION,
    FEE_COMPENSATING,
    FEE_COMPENSATED,
    FEE_COMPENSATION_SKIPPED,

    LIMITS_EVALUATING_COMPENSATION,
    LIMITS_COMPENSATING,
    LIMITS_COMPENSATED,
    LIMITS_COMPENSATION_SKIPPED,

    SETTLEMENT,
    WALLET_SETTLEMENT,
    WALLET_SETTLED,
    LEDGER_NOTIFIED,
    SETTLEMENT_FAILED,
    LEDGER_NOTIFICATION_FAILED,

    COMPLETED,
    FAILED
}
