package com.example.payment.domain.enums;

public enum PaymentEvent {
    INITIATE,
    REDIRECT,
    AUTHORIZE,
    COMPLETE,
    FAIL,

    AUTH_SUCCESS,
    AUTH_REJECT,
    AUTH_FAIL,

    FRAUD_CLEAR,
    FRAUD_ALERT,
    FRAUD_FAIL,

    FX_SUCCESS,
    FX_FAIL,

    LIMITS_CLEAR,
    LIMITS_REJECT,
    LIMITS_FAIL,

    SANCTIONS_PASS,
    SANCTIONS_HIT,
    SANCTIONS_FAIL,

    FEE_CALC_SUCCESS,
    FEE_CALC_FAIL,
    FEE_CHARGE_SUCCESS,
    FEE_CHARGE_FAIL,
    FEE_COMPENSATE_SUCCESS,
    FEE_COMPENSATE_SKIP,

    LIMITS_COMPENSATE_SUCCESS,
    LIMITS_COMPENSATE_SKIP,

    SETTLEMENT_SUCCESS,
    SETTLEMENT_FAIL,
    WALLET_SETTLED_SUCCESS,
    WALLET_SETTLED_FAIL,
    LEDGER_NOTIFY_SUCCESS,
    LEDGER_NOTIFY_FAIL
}
