package com.example.payment.domain.enums;


public enum PaymentEvent {

  INITIATE, REDIRECT, AUTHORIZE, COMPLETE, FAIL, CANCEL, REFUND, AUTH_SUCCESS, AUTH_FAIL, FRAUD_CLEAR, FRAUD_ALERT, FX_SUCCESS, FX_FAIL, LIMITS_CLEAR, LIMITS_REJECT, SANCTIONS_PASS, SANCTIONS_FAIL, FEE_CALC_SUCCESS, FEE_CALC_FAIL, FEE_CHARGE_SUCCESS, FEE_CHARGE_FAIL
}
