package com.example.payment.domain.enums;


public enum PaymentState {

  NEW, PENDING, PROCESSING, AUTH_PENDING, AUTH_APPROVED, AUTH_REJECTED, FRAUD_EVALUATING, FRAUD_PASSED, FRAUD_DETECTED, LIMITS_EVALUATING, LIMITS_OK, LIMITS_EXCEEDED, SANCTIONS_EVALUATING, SANCTIONS_CLEARED, SANCTIONS_HIT, FEE_EVALUATING, FEE_CALCULATED, FEE_CHARGED, FEE_FAILED, FX_CONVERSION, AUTHORIZED, COMPLETED, FAILED, CANCELED, REFUNDED
}
