package com.example.payments.payment.domain.enums;


public enum PaymentEvent {

  INITIATE, REDIRECT, AUTHORIZE, COMPLETE, FAIL, CANCEL, REFUND, AUTH_SUCCESS, AUTH_FAIL, FRAUD_CLEAR, FX_SUCCESS, FX_FAIL, LIMITS_CLEAR, LIMITS_REJECT, SANCTIONS_PASS, SANCTIONS_FAIL, FRAUD_ALERT
}
