package com.example.payments.payment.domain.enums;


public enum PaymentState {

  NEW, PENDING, PROCESSING, AUTH_PENDING, AUTH_APPROVED, AUTH_REJECTED, FRAUD_EVALUATING, FRAUD_PASSED, FRAUD_DETECTED, AUTHORIZED, COMPLETED, FAILED, CANCELED, FX_CONVERSION, LIMITS_EVALUATING, LIMITS_OK, LIMITS_EXCEEDED, SANCTIONS_EVALUATING, SANCTIONS_CLEARED, SANCTIONS_HIT, REFUNDED
}
