package com.example.payments.payment.domain.enums;


public enum PaymentEvent {
  INITIATE, REDIRECT, AUTHORIZE, COMPLETE, FAIL, CANCEL, REFUND, AUTH_SUCCESS, AUTH_FAIL, FRAUD_CLEAR, FRAUD_ALERT, RISK_EVALUATED, ANALYST_APPROVE, ANALYST_REJECT, FUNDS_RESERVED, FUNDS_RESERVATION_FAILED, FEE_RESERVED, FEE_RESERVATION_FAILED, ENTRIES_POSTED, POSTING_FAILED, COMPENSATION_COMPLETE
}
