CREATE TABLE IF NOT EXISTS webhook_configs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT UNIQUE NOT NULL,
    url TEXT NOT NULL,
    secret_signature TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS webhook_delivery_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id BIGINT NOT NULL,
    payment_id BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    http_status_code INT,
    error_message TEXT,
    is_delivered BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_webhook_delivery_logs_payment_id ON webhook_delivery_logs(payment_id);
